services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: muse-backend
    ports:
      - "8010:8000"
    env_file:
      - ./muse_backend/.env
    environment:
      MUSE_VIDEO_HTTP_BASE: "http://frontend:3000"
      MUSE_FRONTEND_BASE_URL: "http://localhost:3000"
      COMFYUI_BASE_URL: "http://host.docker.internal:8000"
      COMFYUI_API_KEY: comfyui-38499822a41adb1c2f0684371d883682d0e36fa4693c79457604b88bb0b9a2fa
    volumes:
      - ./muse_backend:/app/muse_backend
      - ./muse-studio/outputs:/app/muse-studio/outputs
      - ./packages:/app/packages
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: python run.py

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: muse-frontend
    ports:
      - "3000:3000"
    environment:
      MUSE_BACKEND_URL: "http://backend:8000"
      NEXT_PUBLIC_OLLAMA_BASE_URL: "http://host.docker.internal:11434"
      NEXT_PUBLIC_LMSTUDIO_BASE_URL: "http://host.docker.internal:1234"
    volumes:
      - ./muse-studio/outputs:/app/muse-studio/outputs
    depends_on:
      - backend
