'use client';

import { useState, useTransition } from 'react';
import { BookOpen, Sparkles, Upload, PenLine, Users } from 'lucide-react';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { Textarea } from '@/components/ui/textarea';
import { Button } from '@/components/ui/button';
import { updateProject } from '@/lib/actions/projects';
import type { ProjectOverview, StorylineSource } from '@/lib/types';

const STORYLINE_SOURCE_LABELS: Record<StorylineSource, string> = {
  MUSE_GENERATED: 'Generated by Story Muse',
  UPLOAD: 'Uploaded document',
  MANUAL: 'Written manually',
};

export interface ProjectOverviewSheetProps {
  project: ProjectOverview;
  open: boolean;
  onOpenChange: (open: boolean) => void;
  projectId?: string;
}

export function ProjectOverviewSheet({ project, open, onOpenChange, projectId }: ProjectOverviewSheetProps) {
  const { title, description, storyline, storylineSource } = project;
  const characters = storyline?.characters ?? [];

  const [logline, setLogline] = useState(storyline?.logline ?? '');
  const [plotOutline, setPlotOutline] = useState(storyline?.plotOutline ?? '');
  const [genre, setGenre] = useState(storyline?.genre ?? '');
  const [themes, setThemes] = useState((storyline?.themes ?? []).join(', '));
  const [convention, setConvention] = useState(project.promptConvention ?? '');
  const [saveStatus, setSaveStatus] = useState<'idle' | 'saved' | 'error'>('idle');
  const [isPending, startTransition] = useTransition();

  const SourceIcon =
    storylineSource === 'MUSE_GENERATED'
      ? Sparkles
      : storylineSource === 'UPLOAD'
        ? Upload
        : PenLine;

  const isEditable = !!projectId;

  function handleSave() {
    if (!projectId) return;
    startTransition(async () => {
      try {
        await updateProject(projectId, {
          promptConvention: convention,
          storylineLogline: logline,
          storylinePlotOutline: plotOutline,
          storylineGenre: genre,
          storylineThemes: themes
            .split(',')
            .map((t) => t.trim())
            .filter(Boolean),
        });
        setSaveStatus('saved');
        setTimeout(() => setSaveStatus('idle'), 2000);
      } catch {
        setSaveStatus('error');
      }
    });
  }

  return (
    <Sheet open={open} onOpenChange={onOpenChange}>
      <SheetContent
        side="right"
        dismissible={false}
        className="w-[420px] max-w-[95vw] border-white/8 bg-[oklch(0.13_0.012_264)] p-0 flex flex-col"
      >
        <SheetHeader className="border-b border-white/8 px-5 py-4 shrink-0">
          <SheetTitle className="flex items-center gap-2 text-sm font-semibold pr-8">
            <BookOpen className="h-4 w-4 text-violet-400" />
            Project overview
          </SheetTitle>
          <SheetDescription className="text-xs text-muted-foreground">
            {isEditable
              ? 'Edit storyline fields and visual style guide, then save.'
              : 'A quick reminder of this project — title, storyline, and cast.'}
          </SheetDescription>
        </SheetHeader>

        <div className="flex flex-1 flex-col gap-6 overflow-y-auto p-5">
          {/* Title & description */}
          <section>
            <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-1.5">
              Project
            </h3>
            <p className="font-medium text-foreground">{title}</p>
            {description && (
              <p className="mt-1 text-sm text-muted-foreground leading-relaxed">{description}</p>
            )}
          </section>

          {/* Storyline source */}
          <section>
            <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-1.5">
              Storyline source
            </h3>
            <div className="flex items-center gap-2 rounded-lg border border-white/8 bg-white/5 px-3 py-2">
              <SourceIcon className="h-4 w-4 text-violet-400 shrink-0" />
              <span className="text-sm text-foreground/90">
                {STORYLINE_SOURCE_LABELS[storylineSource]}
              </span>
            </div>
          </section>

          {/* Storyline — editable when projectId is set */}
          <section>
            <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-1.5">
              Storyline
            </h3>
            {isEditable ? (
              <div className="space-y-3">
                <div className="space-y-1">
                  <p className="text-[10px] font-semibold text-muted-foreground uppercase">Logline</p>
                  <Textarea
                    value={logline}
                    onChange={(e) => setLogline(e.target.value)}
                    rows={2}
                    placeholder="One-sentence premise of your film."
                    className="resize-none bg-black/20 border-white/10 text-xs placeholder:text-muted-foreground/40"
                  />
                </div>
                <div className="space-y-1">
                  <p className="text-[10px] font-semibold text-muted-foreground uppercase">Plot outline</p>
                  <Textarea
                    value={plotOutline}
                    onChange={(e) => setPlotOutline(e.target.value)}
                    rows={4}
                    placeholder="The full story arc: setup, rising action, climax, resolution."
                    className="resize-none bg-black/20 border-white/10 text-xs placeholder:text-muted-foreground/40"
                  />
                </div>
                <div className="space-y-1">
                  <p className="text-[10px] font-semibold text-muted-foreground uppercase">Genre</p>
                  <input
                    type="text"
                    value={genre}
                    onChange={(e) => setGenre(e.target.value)}
                    placeholder="e.g. Neo-noir thriller"
                    className="w-full rounded-md border border-white/10 bg-black/20 px-3 py-1.5 text-xs placeholder:text-muted-foreground/40 focus:outline-none focus:ring-1 focus:ring-violet-500/50"
                  />
                </div>
                <div className="space-y-1">
                  <p className="text-[10px] font-semibold text-muted-foreground uppercase">Themes</p>
                  <input
                    type="text"
                    value={themes}
                    onChange={(e) => setThemes(e.target.value)}
                    placeholder="e.g. redemption, obsession, identity"
                    className="w-full rounded-md border border-white/10 bg-black/20 px-3 py-1.5 text-xs placeholder:text-muted-foreground/40 focus:outline-none focus:ring-1 focus:ring-violet-500/50"
                  />
                  <p className="text-[10px] text-muted-foreground/50">Comma-separated.</p>
                </div>
              </div>
            ) : !storyline ? (
              <p className="text-sm text-muted-foreground rounded-lg border border-white/8 bg-white/5 px-3 py-4">
                No storyline yet.
              </p>
            ) : (
              <div className="rounded-xl border border-white/8 bg-white/5 p-4 space-y-3 text-sm">
                {storyline.logline && (
                  <div>
                    <p className="text-[10px] font-semibold text-muted-foreground uppercase mb-0.5">Logline</p>
                    <p className="text-foreground/90 leading-relaxed">{storyline.logline}</p>
                  </div>
                )}
                {storyline.plotOutline ? (
                  <div>
                    <p className="text-[10px] font-semibold text-muted-foreground uppercase mb-0.5">Plot outline</p>
                    <p className="text-foreground/90 leading-relaxed whitespace-pre-wrap">{storyline.plotOutline}</p>
                  </div>
                ) : null}
                {storyline.genre && (
                  <div>
                    <p className="text-[10px] font-semibold text-muted-foreground uppercase mb-0.5">Genre</p>
                    <p className="text-foreground/90">{storyline.genre}</p>
                  </div>
                )}
                {storyline.themes?.length > 0 && (
                  <div>
                    <p className="text-[10px] font-semibold text-muted-foreground uppercase mb-0.5">Themes</p>
                    <p className="text-foreground/90">{storyline.themes.join(', ')}</p>
                  </div>
                )}
                {!storyline.logline &&
                  !storyline.plotOutline &&
                  !storyline.genre &&
                  !(storyline.themes?.length) && (
                    <p className="text-muted-foreground">No storyline details yet.</p>
                  )}
              </div>
            )}
          </section>

          {/* Characters */}
          <section>
            <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-1.5 flex items-center gap-1.5">
              <Users className="h-3.5 w-3.5" />
              Characters
            </h3>
            {characters.length === 0 ? (
              <p className="text-sm text-muted-foreground rounded-lg border border-white/8 bg-white/5 px-3 py-4">
                No characters listed.
              </p>
            ) : (
              <ul className="rounded-lg border border-white/8 bg-white/5 px-4 py-3 text-sm text-foreground/90 list-disc list-inside space-y-1">
                {characters.map((c, i) => (
                  <li key={i}>{c}</li>
                ))}
              </ul>
            )}
          </section>

          {/* Visual Style Guide */}
          {isEditable && (
            <section>
              <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-1">
                Visual Style Guide
              </h3>
              <p className="text-[11px] text-muted-foreground/70 mb-1.5">
                Used as project context for visual Muse prompts.
              </p>
              <Textarea
                value={convention}
                onChange={(e) => setConvention(e.target.value)}
                rows={4}
                placeholder="Describe the global visual style, rendering direction, lighting, palette, and constraints for this project."
                className="resize-none bg-black/20 border-white/10 text-xs placeholder:text-muted-foreground/40"
              />
            </section>
          )}
        </div>

        {/* Sticky footer — Save button */}
        {isEditable && (
          <div className="shrink-0 border-t border-white/8 px-5 pt-3 pb-16 flex items-center gap-3">
            {saveStatus === 'error' && (
              <p className="text-xs text-red-400">Failed to save project overview.</p>
            )}
            {saveStatus === 'saved' && (
              <p className="text-xs text-emerald-400">Saved</p>
            )}
            <Button
              size="sm"
              disabled={isPending}
              onClick={handleSave}
              className="ml-auto text-xs"
            >
              {isPending ? 'Saving...' : 'Save changes'}
            </Button>
          </div>
        )}
      </SheetContent>
    </Sheet>
  );
}
